### ISSUE TITLE
Add preview screenshots to the Github repo

### ISSUE THREAD

**Issue by Endo-Heikichi** [lyptt/orbit#181]
Firstly, amazing job conceiving this idea. Rust based forums are a rarity but to find one with ActivityPub support is like finding Pepsi in a desert.

Now, I was wondering if you would consider adding some screenshots of the default forum UI. I realize that server admins are free to tweak things as they please. But I'm curious how things look out-of-box.

**Comment by lyptt** [comment]
Sure! I'll add some screenshots of how it looks at the moment.

**Comment by lyptt** [comment]
I've added screenshots [here](https://github.com/lyptt/orbit/blob/dev/docs/screenshots)
