### ISSUE TITLE
Potential correction to be in the Requirements section 

### ISSUE THREAD

**Issue by Endo-Heikichi** [lyptt/orbit#182]
In the Requirements section, it says that "A CDN" is needed. But this section talks about Amazon S3.

I think a more accurate title for this sub-section is "An Object Store" OR "A file store".

When I read "CDN", I think Cloudflare not S3. Just some feedback.

**Comment by lyptt** [comment]
Good shout! I'll update that. Technically a CDN and a file store are required for it to be optimal, you'll need a public CDN base URL for orbit to construct public links to images, but you could technically get away with any file store that can serve images over HTTP.

**Comment by lyptt** [comment]
I've updated the docs to indicate that what we're actually talking about is a file store backed by some kind of CDN
